spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:gof
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
      show-sql: true

server:
  port: 8081

via:
  cep:
    url: https://viacep.com.br/ws/